language: python
sudo: true

python:
  - 3.8

env:
  global:
    - PIPENV_VENV_IN_PROJECT=1
    - PIPENV_IGNORE_VIRTUALENVS=1

install:
  - pip install pipenv
  - pipenv sync --dev
  - cp contrib/env-sample .env

script:
  - pipenv run flake8
  - pypenv run pytest --cov=pypro

after_sucess:
  - pipenv run codecov